import { useEffect, useState } from "react";
import { Link } from "react-router";
import { Clock, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { PageLayout } from "@/app/components/Layout";
import { useAuth } from "@/app/context/AuthContext";
import { useTheme } from "@/app/context/ThemeContext";
import { isSupabaseConfigured, supabase } from "@/supabaseClient";

type HistoryItem = { id: string; original_input: string; verdict: "safe" | "false" | "misleading" | "unverified"; confidence: number; created_at: string; verification_source: "ai" | "mock_fallback" };
const verdictColor = { safe: "#22C55E", false: "#EF4444", misleading: "#F59E0B", unverified: "#8B5CF6" };

export default function HistoryPage() {
  const { user } = useAuth(); const { isDark } = useTheme();
  const [items, setItems] = useState<HistoryItem[]>([]); const [loading, setLoading] = useState(true); const [removing, setRemoving] = useState<string | null>(null);
  const load = async () => { if (!user || !isSupabaseConfigured || "isDemo" in user) { setLoading(false); return; } setLoading(true); const { data, error } = await supabase.from("verification_history").select("id,original_input,verdict,confidence,created_at,verification_source").order("created_at", { ascending: false }); if (error) toast.error("Could not load verification history."); else setItems((data ?? []) as HistoryItem[]); setLoading(false); };
  useEffect(() => { void load(); }, [user?.id]);
  const remove = async (id: string) => { if (!isSupabaseConfigured) return; setRemoving(id); const previous = items; setItems(current => current.filter(item => item.id !== id)); const { error } = await supabase.from("verification_history").delete().eq("id", id); if (error) { setItems(previous); toast.error("Could not remove this verification."); } else toast.success("Verification removed."); setRemoving(null); };
  const card = isDark ? "border-white/10 bg-white/4" : "border-slate-200 bg-white";
  return <PageLayout><div className="min-h-screen px-4 pb-16 pt-24 sm:px-6 lg:px-8" style={{ background: "var(--tng-page)" }}><div className="mx-auto max-w-4xl"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-[#F5B800]">Personal record</p><h1 className="text-3xl font-extrabold" style={{ color: "var(--tng-text-1)" }}>Verification History</h1><p className={`mt-2 text-sm ${isDark ? "text-blue-200/60" : "text-[#5F7AA8]"}`}>Your saved analyses are private and available across sessions.</p></div><Link to="/verify" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-[#F5B800] px-4 py-2.5 text-sm font-bold text-[#050E24]"><Search size={15} />Verify</Link></div>{loading ? <div className={`rounded-2xl border p-8 text-sm ${card}`}>Loading saved verifications…</div> : items.length === 0 ? <div className={`rounded-2xl border p-10 text-center ${card}`}><Clock className="mx-auto mb-3 text-[#F5B800]" /><p className="font-bold" style={{ color: "var(--tng-text-1)" }}>No saved verifications yet</p><p className={`mt-2 text-sm ${isDark ? "text-blue-200/60" : "text-[#5F7AA8]"}`}>Save an analysis from the verification results to see it here.</p></div> : <div className="space-y-3">{items.map(item => <article key={item.id} className={`rounded-2xl border p-5 ${card}`}><div className="flex items-start gap-4"><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><span className="rounded-full px-2 py-0.5 text-[10px] font-extrabold uppercase" style={{ background: `${verdictColor[item.verdict]}22`, color: verdictColor[item.verdict] }}>{item.verdict}</span><span className="text-xs font-semibold" style={{ color: verdictColor[item.verdict] }}>{item.confidence}% confidence</span><span className={`text-xs ${isDark ? "text-blue-200/40" : "text-slate-400"}`}>{new Date(item.created_at).toLocaleString()}</span></div><p className={`line-clamp-2 text-sm ${isDark ? "text-blue-100/80" : "text-[#2E4A7A]"}`}>{item.original_input}</p><p className={`mt-2 text-[11px] ${isDark ? "text-blue-200/40" : "text-slate-400"}`}>{item.verification_source === "ai" ? "AI analysis" : "Offline fallback"}</p></div><button disabled={removing === item.id} onClick={() => void remove(item.id)} aria-label="Remove verification" className="rounded-lg p-2 text-slate-400 hover:bg-red-500/10 hover:text-red-400 disabled:opacity-50"><Trash2 size={16} /></button></div></article>)}</div>}</div></div></PageLayout>;
}
